version: '3'
services:
  
  app:
    build: app/.
    depends_on:
      - db

    environment:
     - SQLALCHEMY_DATABASE_URI=mysql://root:password@db/s3monitor
     - APP_SECRET_KEY=x$ffiDFXewip1ze7Mddei22hsdsd4k
     - SQLALCHEMY_TRACK_MODIFICATIONS=True

  db:
    restart: always
    image: mysql:5.7
    volumes:
      - /var/lib/mysql2:/var/lib/mysql
    environment:
       MYSQL_DATABASE: "s3monitor"
       MYSQL_ROOT_PASSWORD: password

  www:
    restart: always
    build: nginx/.
    links:
      - app
    depends_on:
      - app
    ports:
      - "80:80"
